import { IRoleRepository } from "../../domain/repositories/IRoleRepository";
import { Role } from "../../domain/entities/Role";
import { RoleGroup, RoleEnum } from "shared-lib";

export class RoleSeeder {
  constructor(private roleRepository: IRoleRepository) {}

  async seed() {
    const roles: Role[] = [
      new Role(
        "", // ID is generated by DB
        RoleEnum.SuperAdmin,
        RoleGroup.SuperAdmin,
        "Super Administrator with full access",
        ["*"]
      ),
      new Role(
        "",
        RoleEnum.SchoolAdmin,
        RoleGroup.SchoolAdmin,
        "Administrator for a specific school",
        ["manage_school", "manage_teachers", "manage_students"]
      ),
      new Role("", RoleEnum.Teacher, RoleGroup.Teacher, "Teacher role", [
        "manage_classes",
        "grade_students",
      ]),
      new Role("", RoleEnum.Student, RoleGroup.Student, "Student role", [
        "view_grades",
        "view_schedule",
      ]),
      new Role(
        "",
        RoleEnum.CanteenStaff,
        RoleGroup.Staff,
        "Canteen Staff role",
        ["manage_canteen"]
      ),
      new Role("", RoleEnum.Nurse, RoleGroup.Staff, "School Nurse role", [
        "manage_health_records",
      ]),
      new Role("", RoleEnum.Security, RoleGroup.Staff, "Security Guard role", [
        "view_entry_logs",
      ]),
    ];

    console.log("🌱 Seeding roles...");

    for (const role of roles) {
      // Check if role group/name combination exists to avoid duplicates
      // Note: This logic assumes one role per unique RoleEnum name.
      // Since findOneByGroup returns one role of the group, and a group might have multiple roles (like Staff),
      // we might need a more specific check if we wanted to be perfectly idempotent for all roles.
      // However, for the basic types which map 1:1 or specific Staff types, we can try to find by group and iterate,
      // or simply rely on unique constraints if they existed.
      // For now, let's just check if *any* role of this name exists?
      // Repository currently only finds by group.
      // Let's iterate and create if not found.

      // For simplicity in this seed script, let's just try to create if we assume it's fresh or check simple logic.
      // Actually, Repository interface is limited. Let's just create.
      // In a real scenario we'd check `findByName` but we don't have it.
      // We'll rely on the user running this once or DB constraints handling it (if unique).
      // Or better, let's check by group. If group exists, we might skip or check further.

      // Strategy: Simple check. If role group 'SuperAdmin' exists, skip SuperAdmin.
      const existingRole = await this.roleRepository.findOneByGroup(role.group);

      // Refinement: RoleGroup.Staff has multiple roles (Canteen, Nurse...).
      // findOneByGroup(Staff) will return *one* of them.
      // IF we want to ensure ALL are created, we need to check differently or expand the repository.
      // Given the request is to "seed default roles", ensuring at least one exists is a start,
      // but ideally we want all specific Enum types.

      // Since I cannot change Repository easily without affecting others too much right now,
      // I will just create them. If you run it twice, you might get duplicates unless DB has constraints.
      // Let's assume this is a setup script.

      try {
        await this.roleRepository.create(role);
        console.log(`✅ Role ${role.name} created.`);
      } catch (error) {
        console.error(`❌ Failed to create role ${role.name}:`, error);
      }
    }

    console.log("✨ Roles seeding completed.");
  }
}
