import { ISchoolRepository } from "../../repositories/ISchoolRepository";
import { CreateSchoolDto } from "../../../presentation/dtos/CreateSchoolDto";
import { School } from "../../entities/School";

import { CodeGeneratorUtil } from "../../../infrastructure/utils/CodeGeneratorUtil";

export class RegisterSchoolUseCase {
  constructor(private schoolRepository: ISchoolRepository) {}

  async execute(dto: CreateSchoolDto): Promise<School> {
    const code = dto.code || CodeGeneratorUtil.generateSchoolCode(dto.name);

    // Check if school code exists
    const existingSchool = await this.schoolRepository.findByCode(code);
    if (existingSchool) {
      throw new Error("School code already exists");
    }

    const school = new School(
      "", // ID generated by DB
      dto.name,
      code,
      dto.address,
      dto.level,
      dto.adminId,
      dto.phone,
      dto.description,
      dto.logoUrl,
      0, // studentCount
      dto.customTheme
    );

    return await this.schoolRepository.create(school);
  }
}
