import { IGradeRepository } from "../../repositories/IGradeRepository";
import { CreateGradeDto } from "../../../presentation/dtos/CreateGradeDto";
import { Grade } from "../../entities/Grade";

export class CreateGradeUseCase {
  constructor(private gradeRepository: IGradeRepository) {}

  async execute(dto: CreateGradeDto): Promise<Grade> {
    const grade = new Grade(
      "", // ID generated by DB
      dto.schoolId,
      dto.name,
      dto.level,
      dto.gradeGroup,
      dto.order,
      dto.active ?? true,
      dto.ageRange,
      dto.description,
      dto.customFields
    );

    return await this.gradeRepository.create(grade);
  }
}
