import { IUserRepository } from "../../repositories/IUserRepository";
import { CreateUserDto } from "../../../presentation/dtos/CreateUserDto";
import { User } from "../../entities/User";

export class CreateUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  async execute(dto: CreateUserDto): Promise<User> {
    // Basic validation or business logic here
    // e.g. check if email exists (if not handled by repo/db constraint)

    const user = new User(
      "", // ID generated by DB
      dto.fullName,
      dto.roleKey,
      dto.email,
      dto.gender,
      dto.birthday,
      dto.phone,
      dto.address,
      false, // isVerified default
      dto.avatarUrl,
      dto.schoolId
    );

    return await this.userRepository.create(user);
  }
}
