import { IUserRepository } from "../../repositories/IUserRepository";
import { CreateUserDto } from "../../../presentation/dtos/CreateUserDto";
import { User } from "../../entities/User";

import { IRoleRepository } from "../../repositories/IRoleRepository";

export class CreateUserUseCase {
  constructor(
    private userRepository: IUserRepository,
    private roleRepository: IRoleRepository
  ) {}

  async execute(dto: CreateUserDto): Promise<User> {
    // Basic validation or business logic here
    // e.g. check if email exists (if not handled by repo/db constraint)

    const role = await this.roleRepository.findOneByGroup(dto.roleKey);
    if (!role) {
      throw new Error(`Role not found for group: ${dto.roleKey}`);
    }

    const user = new User(
      "", // ID generated by DB
      dto.fullName,
      dto.roleKey,
      role.id,
      dto.email,
      dto.gender,
      dto.birthday,
      dto.phone,
      dto.address,
      false, // isVerified default
      dto.avatarUrl,
      dto.schoolId
    );

    return await this.userRepository.create(user);
  }
}
