import { IUserRepository } from "../../repositories/IUserRepository";
import { User } from "../../entities/User";
import { Account } from "../../entities/Account";
import { AuthUtils } from "../../../infrastructure/utils/AuthUtils";
import { S3Utils } from "../../../infrastructure/utils/S3Utils";
import { v4 as uuidv4 } from "uuid";
import { RoleGroup } from "shared-lib";

export interface RegisterUserRequest {
  email: string;
  password: string;
  fullName: string;
  roleKey: RoleGroup;
  gender?: string;
  birthday?: Date;
  phone?: string;
  address?: string;
  schoolId?: string;
  avatarFile?: {
    buffer: Buffer;
    mimetype: string;
  };
}

export interface RegisterUserResponse {
  user: User;
  account: Account;
  tokens: {
    accessToken: string;
    refreshToken: string;
  };
}

export class RegisterUserUseCase {
  constructor(private userRepository: IUserRepository) {}

  async execute(request: RegisterUserRequest): Promise<RegisterUserResponse> {
    // 1. Check if email already exists
    const existingAccount = await this.userRepository.findAccountByEmail(
      request.email
    );
    if (existingAccount) {
      throw new Error("Email already registered");
    }

    // 2. Hash password
    const passwordHash = await AuthUtils.hashPassword(request.password);

    // 3. Generate unique UID for the account
    const uid = uuidv4();

    // 4. Upload avatar to S3 if provided (will be updated after user creation)
    let avatarUrl: string | undefined;

    // 5. Create User entity
    const user = new User(
      "", // ID will be generated by database
      request.fullName,
      request.roleKey,
      request.email,
      request.gender as any,
      request.birthday,
      request.phone,
      request.address,
      false, // isVerified
      avatarUrl,
      request.schoolId || null
    );

    // 6. Create user in database
    const createdUser = await this.userRepository.create(user);

    // 7. Upload avatar with user ID if provided
    if (request.avatarFile) {
      const { url } = await S3Utils.uploadAvatar(
        createdUser.id,
        request.avatarFile.buffer,
        request.avatarFile.mimetype
      );
      avatarUrl = url;

      // Update user with avatar URL
      await this.userRepository.updateAvatar(createdUser.id, avatarUrl);
      createdUser.avatarUrl = avatarUrl;
    }

    // 8. Create Account entity
    const account = new Account(
      "", // ID will be generated by database
      createdUser.id,
      request.email,
      passwordHash,
      uid,
      true, // isActive
      undefined // lastLogin
    );

    // 9. Create account in database
    const createdAccount = await this.userRepository.createAccount(account);

    // 10. Generate JWT tokens
    const tokens = AuthUtils.generateTokenPair({
      userId: createdUser.id,
      email: createdUser.email || request.email,
      roleKey: createdUser.roleKey,
    });

    return {
      user: createdUser,
      account: createdAccount,
      tokens,
    };
  }
}
