import { IUserRepository } from "../../repositories/IUserRepository";
import { IMembershipRequestRepository } from "../../repositories/IMembershipRequestRepository";
import { MembershipRequest } from "../../entities/MembershipRequest";
import {
  MembershipRoleEnum,
  MembershipActionEnum,
  MembershipStatusEnum,
} from "shared-lib";
import { User } from "../../entities/User";
import { Account } from "../../entities/Account";
import { AuthUtils } from "../../../infrastructure/utils/AuthUtils";
import { S3Utils } from "../../../infrastructure/utils/S3Utils";
import { v4 as uuidv4 } from "uuid";
import { RoleGroup } from "shared-lib";

export interface RegisterUserRequest {
  email: string;
  password: string;
  fullName: string;
  roleKey: RoleGroup;
  gender?: string;
  birthday?: Date;
  phone?: string;
  address?: string;
  schoolId?: string;
  classId?: string;
  avatarFile?: {
    buffer: Buffer;
    mimetype: string;
  };
  specificInfo?: any;
  schoolData?: {
    name: string;
    address: string;
    phone?: string;
    description?: string;
    level: string;
  };
}

export interface RegisterUserResponse {
  user: User;
  account: Account;
  tokens: {
    accessToken: string;
    refreshToken: string;
  };
}

export class RegisterUserUseCase {
  constructor(
    private userRepository: IUserRepository,
    private membershipRepository: IMembershipRequestRepository
  ) {}

  async execute(request: RegisterUserRequest): Promise<RegisterUserResponse> {
    // 1. Check if email already exists
    const existingAccount = await this.userRepository.findAccountByEmail(
      request.email
    );
    if (existingAccount) {
      throw new Error("Email already registered");
    }

    // 2. Hash password
    const passwordHash = await AuthUtils.hashPassword(request.password);

    // 3. Generate unique UID for the account
    const uid = uuidv4();

    // 4. Upload avatar to S3 if provided (will be updated after user creation)
    let avatarUrl: string | undefined;

    // 5. Create User entity
    const user = new User(
      "", // ID will be generated by database
      request.fullName,
      request.roleKey,
      request.email,
      request.gender as any,
      request.birthday,
      request.phone,
      request.address,
      false, // isVerified
      avatarUrl,
      request.schoolId || null
    );

    // 6. Create user in database
    const createdUser = await this.userRepository.create(user);

    // 7. Upload avatar with user ID if provided
    if (request.avatarFile) {
      const { url } = await S3Utils.uploadAvatar(
        createdUser.id,
        request.avatarFile.buffer,
        request.avatarFile.mimetype
      );
      avatarUrl = url;

      // Update user with avatar URL
      await this.userRepository.updateAvatar(createdUser.id, avatarUrl);
      createdUser.avatarUrl = avatarUrl;
    }

    // 8. Create Account entity
    const account = new Account(
      "", // ID will be generated by database
      createdUser.id,
      request.email,
      passwordHash,
      uid,
      true, // isActive
      undefined // lastLogin
    );

    // 9. Create account in database
    const createdAccount = await this.userRepository.createAccount(account);

    // 10. Generate JWT tokens
    const tokens = AuthUtils.generateTokenPair({
      userId: createdUser.id,
      email: createdUser.email || request.email,
      roleKey: createdUser.roleKey,
    });

    // 11. Handle school creation for SchoolAdmin
    let finalSchoolId = request.schoolId;
    if (request.roleKey === RoleGroup.SchoolAdmin && request.schoolData) {
      // Create new school
      const newSchool = await this.userRepository.createSchool({
        name: request.schoolData.name,
        address: request.schoolData.address,
        phone: request.schoolData.phone,
        description: request.schoolData.description,
        level: request.schoolData.level,
      });
      finalSchoolId = newSchool.id;

      // Update user with school ID
      await this.userRepository.updateUserSchool(createdUser.id, finalSchoolId);
      createdUser.schoolId = finalSchoolId;
    }

    // 12. Handle Role Specific Logic (Profile & Membership)
    if (request.specificInfo) {
      switch (request.roleKey) {
        case RoleGroup.Student:
          await this.userRepository.createStudentProfile(
            createdUser.id,
            request.specificInfo
          );
          if (finalSchoolId) {
            await this.membershipRepository.create(
              new MembershipRequest(
                "",
                createdUser.id,
                finalSchoolId,
                MembershipRoleEnum.Student,
                MembershipActionEnum.Enroll,
                MembershipStatusEnum.Pending,
                request.classId || undefined, // classId
                undefined, // note
                undefined, // createdAt
                undefined // updatedAt
              )
            );
          }
          break;
        case RoleGroup.Teacher:
          await this.userRepository.createTeacherProfile(
            createdUser.id,
            request.specificInfo
          );
          if (finalSchoolId) {
            await this.membershipRepository.create(
              new MembershipRequest(
                "",
                createdUser.id,
                finalSchoolId,
                MembershipRoleEnum.Teacher,
                MembershipActionEnum.Enroll,
                MembershipStatusEnum.Pending
              )
            );
          }
          break;
        case RoleGroup.SchoolAdmin:
          await this.userRepository.createSchoolAdminProfile(
            createdUser.id,
            request.specificInfo
          );
          // SchoolAdmin creating school is auto-approved
          if (request.schoolData && finalSchoolId) {
            await this.membershipRepository.create(
              new MembershipRequest(
                "",
                createdUser.id,
                finalSchoolId,
                MembershipRoleEnum.SchoolAdmin,
                MembershipActionEnum.Enroll,
                MembershipStatusEnum.Approved
              )
            );
          } else if (finalSchoolId) {
            // SchoolAdmin joining existing school needs approval
            await this.membershipRepository.create(
              new MembershipRequest(
                "",
                createdUser.id,
                finalSchoolId,
                MembershipRoleEnum.SchoolAdmin,
                MembershipActionEnum.Enroll,
                MembershipStatusEnum.Pending
              )
            );
          }
          break;
        case RoleGroup.Staff:
          if (finalSchoolId) {
            await this.membershipRepository.create(
              new MembershipRequest(
                "",
                createdUser.id,
                finalSchoolId,
                MembershipRoleEnum.Staff,
                MembershipActionEnum.Enroll,
                MembershipStatusEnum.Pending
              )
            );
          }
          break;
      }
    }

    return {
      user: createdUser,
      account: createdAccount,
      tokens,
    };
  }
}
