import { IClassRepository } from "../../repositories/IClassRepository";
import { CreateClassDto } from "../../../presentation/dtos/CreateClassDto";
import { Class } from "../../entities/Class";

export class CreateClassUseCase {
  constructor(private classRepository: IClassRepository) {}

  async execute(dto: CreateClassDto): Promise<Class> {
    // Check if class code exists
    const existingClass = await this.classRepository.findByCode(dto.code);
    if (existingClass) {
      throw new Error("Class code already exists");
    }

    const classEntity = new Class(
      "", // ID generated by DB
      dto.name,
      dto.code,
      dto.schoolId,
      dto.gradeId,
      dto.maxStudents ?? 30,
      dto.baseFee ?? 0
    );

    return await this.classRepository.create(classEntity);
  }
}
